[package]
name = "parser"
version = "0.1.0"
edition = "2021"

[dependencies]
pnet = "0.28.0"
byteorder = "1.4"
clap = { version = "4.1", features = ["derive"] }
pcap-file = "2.0.0-rc1"
isin = "0.1.18"